"""empty message

Revision ID: 865fc99377ff
Revises: e2e8e1a44016
Create Date: 2019-07-25 17:00:54.718994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865fc99377ff'
down_revision = 'e2e8e1a44016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('min_time', sa.Integer(), nullable=True),
    sa.Column('blocked_sites', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.username'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
